### ISSUE TITLE
对于空对象的处理

### ISSUE THREAD

**Issue by jeffxjli** [calidion/node-form-validator#4]
您好，特殊情况如下是：
conf = {};
query = {};
var error = validator.validate(query, conf);
error应该是object 其中code是否按照格式
但是上述情况error貌似返回了false。能否按照返回error统一处理？谢谢

**Comment by calidion** [comment]
你用的是那个版本？最新版本应该返回是error对象。

**Comment by jeffxjli** [comment]
试了最新版本，空对象的时候仍然返回false。
https://github.com/calidion/node-form-validator/blob/master/lib/index.js#L29

**Comment by calidion** [comment]
谢谢。
理论上这样处理是合适的。
因为检验本身并没有发生。
所以并没有错，但是校验器也没有工作，所以也不是对的。
如果有好的建议，欢迎提供。

**Comment by calidion** [comment]
issue关闭。如果疑问请直接回复。
